package Ventana;

import Classes.Congelados;
import Classes.Frescos;
import Classes.Productos;
import Classes.Refrigerados;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vicente
 */

public class CargaDeProductos extends javax.swing.JFrame {

    /**
     * Creates new form CargaDeProductos
     */
     Map <Integer, Productos> registros = new HashMap<> (); 
    public CargaDeProductos() {
        initComponents();
        leer_cargados();
    }
   void escribir_cargados() {
       FileOutputStream fo = null;
         try {
             File archivo = new File("Productos.txt");
             fo = new FileOutputStream(archivo);
             BufferedOutputStream bo= new BufferedOutputStream(fo);
             ObjectOutputStream ou= new ObjectOutputStream(bo);
             ou.writeObject(registros);
             bo.flush();
         } catch (Exception ex) {
             Logger.getLogger(CargaDeProductos.class.getName()).log(Level.SEVERE, null, ex);
         } finally {
             try {
                 fo.close();
             } catch (IOException ex) {
                 Logger.getLogger(CargaDeProductos.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
    }

   void leer_cargados() {
       FileInputStream fo = null;
         try {
             File archivo = new File("Productos.txt");
             fo = new FileInputStream(archivo);
             BufferedInputStream bo= new BufferedInputStream(fo);
             ObjectInputStream ou= new ObjectInputStream(bo);
             registros= ( Map <Integer, Productos>) ou.readObject();
             if(registros==null){
                 registros= new HashMap<>();
             }
         } catch (Exception ex) {
             
         } finally {
             try {
                 if(fo != null)
                 fo.close();
                 
             } catch (IOException ex) {
               
             }
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Frescos = new javax.swing.JTabbedPane();
        Productos_Frescos = new javax.swing.JPanel();
        Nombre_Producto = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        Fecha_Envasado = new javax.swing.JLabel();
        Fecha_Caducidad = new javax.swing.JLabel();
        Numero_Lote = new javax.swing.JLabel();
        Pais_Origen = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        Lectura_Nombre = new javax.swing.JTextField();
        Lectura_Descripcion = new javax.swing.JTextField();
        Lectura_Lote = new javax.swing.JTextField();
        Lectura_Pais = new javax.swing.JTextField();
        Lectura_Precio = new javax.swing.JTextField();
        Lectura_Fecha = new com.toedter.calendar.JDateChooser();
        Lectura_Fecha1 = new com.toedter.calendar.JDateChooser();
        Guardar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        Productos_Refrigerados = new javax.swing.JPanel();
        Nombre_Producto1 = new javax.swing.JLabel();
        Fecha_Caducidad1 = new javax.swing.JLabel();
        Numero_Lote1 = new javax.swing.JLabel();
        Descripcion1 = new javax.swing.JLabel();
        Codigo_Organismo = new javax.swing.JLabel();
        Precio1 = new javax.swing.JLabel();
        Lectura_Nombre1 = new javax.swing.JTextField();
        Lectura_Descripcion1 = new javax.swing.JTextField();
        Lectura_Lote1 = new javax.swing.JTextField();
        Lectura_Precio1 = new javax.swing.JTextField();
        Lectura_Fecha3 = new com.toedter.calendar.JDateChooser();
        Guardar1 = new javax.swing.JButton();
        jtfCodigoDeOrganismo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigoRefrigerados = new javax.swing.JTextField();
        buscarRefrigerados = new javax.swing.JButton();
        modificarRefrigerados = new javax.swing.JButton();
        EliminarRefrigerado = new javax.swing.JButton();
        Productos_Congelados = new javax.swing.JPanel();
        Nombre_Producto2 = new javax.swing.JLabel();
        Fecha_Caducidad2 = new javax.swing.JLabel();
        Numero_Lote2 = new javax.swing.JLabel();
        Descripcion2 = new javax.swing.JLabel();
        Temperatura_Recomendada = new javax.swing.JLabel();
        Precio2 = new javax.swing.JLabel();
        Lectura_Nombre2 = new javax.swing.JTextField();
        Lectura_Descripcion2 = new javax.swing.JTextField();
        Lectura_Lote2 = new javax.swing.JTextField();
        Lectura_Temperatura = new javax.swing.JTextField();
        Lectura_Precio2 = new javax.swing.JTextField();
        Lectura_Fecha4 = new com.toedter.calendar.JDateChooser();
        Guardar2 = new javax.swing.JButton();
        BuscarCongelados = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfCodigoCongelados = new javax.swing.JTextField();
        ModificarCongelados = new javax.swing.JButton();
        EliminarCongelados = new javax.swing.JButton();
        Cabecera = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nombre_Producto.setText("Nombre");

        Descripcion.setText("Descripcion");

        Fecha_Envasado.setText("Fecha de Envasado");

        Fecha_Caducidad.setText("Fecha de Caducidad");

        Numero_Lote.setText("Numero de Lote");

        Pais_Origen.setText("Pais de Origen");

        Precio.setText("Precio");

        Lectura_Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_NombreFocusLost(evt);
            }
        });

        Lectura_Descripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_DescripcionFocusLost(evt);
            }
        });
        Lectura_Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lectura_DescripcionActionPerformed(evt);
            }
        });

        Lectura_Lote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_LoteFocusLost(evt);
            }
        });

        Lectura_Pais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_PaisFocusLost(evt);
            }
        });

        Lectura_Precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_PrecioFocusLost(evt);
            }
        });
        Lectura_Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lectura_PrecioActionPerformed(evt);
            }
        });

        Lectura_Fecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_FechaFocusLost(evt);
            }
        });

        Lectura_Fecha1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Fecha1FocusLost(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo del producto");

        jtfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusLost(evt);
            }
        });
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Productos_FrescosLayout = new javax.swing.GroupLayout(Productos_Frescos);
        Productos_Frescos.setLayout(Productos_FrescosLayout);
        Productos_FrescosLayout.setHorizontalGroup(
            Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Productos_FrescosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Productos_FrescosLayout.createSequentialGroup()
                        .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_Producto)
                            .addComponent(Descripcion)
                            .addComponent(Fecha_Envasado)
                            .addComponent(Fecha_Caducidad)
                            .addComponent(Numero_Lote)
                            .addComponent(Pais_Origen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lectura_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lectura_Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(jtfCodigo)
                                .addComponent(Lectura_Nombre))
                            .addComponent(Lectura_Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lectura_Lote, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lectura_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lectura_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(Buscar)
                        .addGap(198, 198, 198))
                    .addGroup(Productos_FrescosLayout.createSequentialGroup()
                        .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Productos_FrescosLayout.createSequentialGroup()
                                .addComponent(Eliminar)
                                .addGap(98, 98, 98)
                                .addComponent(Modificar)
                                .addGap(108, 108, 108)
                                .addComponent(Guardar))
                            .addComponent(Precio))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Productos_FrescosLayout.setVerticalGroup(
            Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Productos_FrescosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addGap(4, 4, 4)
                .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_Producto)
                    .addComponent(Lectura_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lectura_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripcion))
                .addGap(18, 18, 18)
                .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lectura_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha_Envasado))
                .addGap(25, 25, 25)
                .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fecha_Caducidad)
                    .addComponent(Lectura_Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero_Lote)
                    .addComponent(Lectura_Lote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pais_Origen)
                    .addComponent(Lectura_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lectura_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Precio))
                .addGap(45, 45, 45)
                .addGroup(Productos_FrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(Modificar)
                    .addComponent(Guardar))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Frescos.addTab("Frescos", Productos_Frescos);

        Nombre_Producto1.setText("Nombre");

        Fecha_Caducidad1.setText("Fecha de Caducidad");

        Numero_Lote1.setText("Numero de Lote");

        Descripcion1.setText("Descripcion");

        Codigo_Organismo.setText("Codigo del Organismo");

        Precio1.setText("Precio");

        Lectura_Nombre1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Nombre1FocusLost(evt);
            }
        });

        Lectura_Descripcion1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Descripcion1FocusLost(evt);
            }
        });
        Lectura_Descripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lectura_Descripcion1ActionPerformed(evt);
            }
        });

        Lectura_Lote1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Lote1FocusLost(evt);
            }
        });

        Lectura_Precio1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Precio1FocusLost(evt);
            }
        });
        Lectura_Precio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lectura_Precio1ActionPerformed(evt);
            }
        });

        Lectura_Fecha3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Fecha3FocusLost(evt);
            }
        });

        Guardar1.setText("Guardar");
        Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar1ActionPerformed(evt);
            }
        });

        jtfCodigoDeOrganismo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoDeOrganismoFocusLost(evt);
            }
        });

        jLabel2.setText("Codigo del producto");

        jtfCodigoRefrigerados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoRefrigeradosFocusLost(evt);
            }
        });
        jtfCodigoRefrigerados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoRefrigeradosActionPerformed(evt);
            }
        });

        buscarRefrigerados.setText("Buscar");
        buscarRefrigerados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarRefrigeradosActionPerformed(evt);
            }
        });

        modificarRefrigerados.setText("Modificar");
        modificarRefrigerados.setActionCommand("");
        modificarRefrigerados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarRefrigeradosActionPerformed(evt);
            }
        });

        EliminarRefrigerado.setText("Eliminar");
        EliminarRefrigerado.setActionCommand("E");
        EliminarRefrigerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarRefrigeradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Productos_RefrigeradosLayout = new javax.swing.GroupLayout(Productos_Refrigerados);
        Productos_Refrigerados.setLayout(Productos_RefrigeradosLayout);
        Productos_RefrigeradosLayout.setHorizontalGroup(
            Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Productos_RefrigeradosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Productos_RefrigeradosLayout.createSequentialGroup()
                            .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nombre_Producto1)
                                .addComponent(Descripcion1)
                                .addComponent(Fecha_Caducidad1)
                                .addComponent(Numero_Lote1))
                            .addGap(28, 28, 28))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Productos_RefrigeradosLayout.createSequentialGroup()
                            .addComponent(Codigo_Organismo)
                            .addGap(18, 18, 18)))
                    .addGroup(Productos_RefrigeradosLayout.createSequentialGroup()
                        .addComponent(Precio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lectura_Fecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Lectura_Descripcion1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(Lectura_Nombre1))
                    .addComponent(Lectura_Lote1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCodigoDeOrganismo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lectura_Precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 327, Short.MAX_VALUE))
            .addGroup(Productos_RefrigeradosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfCodigoRefrigerados, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(buscarRefrigerados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Productos_RefrigeradosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(EliminarRefrigerado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(modificarRefrigerados)
                .addGap(125, 125, 125)
                .addComponent(Guardar1)
                .addGap(61, 61, 61))
        );
        Productos_RefrigeradosLayout.setVerticalGroup(
            Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Productos_RefrigeradosLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCodigoRefrigerados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarRefrigerados))
                .addGap(20, 20, 20)
                .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_Producto1)
                    .addComponent(Lectura_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lectura_Descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripcion1))
                .addGap(18, 18, 18)
                .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lectura_Fecha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha_Caducidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lectura_Lote1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero_Lote1))
                .addGap(18, 18, 18)
                .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigoDeOrganismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codigo_Organismo))
                .addGap(18, 18, 18)
                .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lectura_Precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Precio1))
                .addGap(48, 48, 48)
                .addGroup(Productos_RefrigeradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarRefrigerado)
                    .addComponent(modificarRefrigerados)
                    .addComponent(Guardar1))
                .addGap(82, 82, 82))
        );

        Frescos.addTab("Refrigerados", Productos_Refrigerados);

        Nombre_Producto2.setText("Nombre");

        Fecha_Caducidad2.setText("Fecha de Caducidad");

        Numero_Lote2.setText("Numero de Lote");

        Descripcion2.setText("Descripcion");

        Temperatura_Recomendada.setText("Temperatura Recomendada");

        Precio2.setText("Precio");

        Lectura_Nombre2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Nombre2FocusLost(evt);
            }
        });

        Lectura_Descripcion2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Descripcion2FocusLost(evt);
            }
        });
        Lectura_Descripcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lectura_Descripcion2ActionPerformed(evt);
            }
        });

        Lectura_Lote2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Lote2FocusLost(evt);
            }
        });

        Lectura_Temperatura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_TemperaturaFocusLost(evt);
            }
        });

        Lectura_Precio2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Precio2FocusLost(evt);
            }
        });
        Lectura_Precio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lectura_Precio2ActionPerformed(evt);
            }
        });

        Lectura_Fecha4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lectura_Fecha4FocusLost(evt);
            }
        });

        Guardar2.setText("Guardar");
        Guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar2ActionPerformed(evt);
            }
        });

        BuscarCongelados.setText("Buscar");
        BuscarCongelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCongeladosActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo del producto");

        jtfCodigoCongelados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoCongeladosFocusLost(evt);
            }
        });
        jtfCodigoCongelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoCongeladosActionPerformed(evt);
            }
        });

        ModificarCongelados.setText("Modificar");
        ModificarCongelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarCongeladosActionPerformed(evt);
            }
        });

        EliminarCongelados.setText("Eliminar");
        EliminarCongelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCongeladosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Productos_CongeladosLayout = new javax.swing.GroupLayout(Productos_Congelados);
        Productos_Congelados.setLayout(Productos_CongeladosLayout);
        Productos_CongeladosLayout.setHorizontalGroup(
            Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Productos_CongeladosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Productos_CongeladosLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfCodigoCongelados, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BuscarCongelados))
                    .addGroup(Productos_CongeladosLayout.createSequentialGroup()
                        .addComponent(Nombre_Producto2)
                        .addGap(93, 93, 93)
                        .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lectura_Fecha4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lectura_Descripcion2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(Lectura_Nombre2))
                            .addComponent(Lectura_Lote2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Productos_CongeladosLayout.createSequentialGroup()
                        .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Descripcion2)
                            .addComponent(Fecha_Caducidad2)
                            .addComponent(Temperatura_Recomendada)
                            .addComponent(Numero_Lote2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lectura_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Productos_CongeladosLayout.createSequentialGroup()
                        .addComponent(Precio2)
                        .addGap(105, 105, 105)
                        .addComponent(Lectura_Precio2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Productos_CongeladosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(EliminarCongelados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(ModificarCongelados)
                .addGap(130, 130, 130)
                .addComponent(Guardar2)
                .addGap(57, 57, 57))
        );
        Productos_CongeladosLayout.setVerticalGroup(
            Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Productos_CongeladosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCodigoCongelados, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarCongelados))
                .addGap(18, 18, 18)
                .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre_Producto2)
                    .addComponent(Lectura_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descripcion2)
                    .addComponent(Lectura_Descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fecha_Caducidad2)
                    .addComponent(Lectura_Fecha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero_Lote2)
                    .addComponent(Lectura_Lote2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lectura_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Temperatura_Recomendada))
                .addGap(21, 21, 21)
                .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio2)
                    .addComponent(Lectura_Precio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(Productos_CongeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarCongelados)
                    .addComponent(ModificarCongelados)
                    .addComponent(Guardar2))
                .addGap(83, 83, 83))
        );

        Frescos.addTab("Congelados", Productos_Congelados);

        Cabecera.setText("Carga de productos");

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(Cabecera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Regresar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Frescos, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Regresar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Frescos, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lectura_DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lectura_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lectura_DescripcionActionPerformed

    private void Lectura_PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lectura_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lectura_PrecioActionPerformed

    private void Lectura_Descripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lectura_Descripcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lectura_Descripcion1ActionPerformed

    private void Lectura_Precio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lectura_Precio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lectura_Precio1ActionPerformed

    private void Lectura_Descripcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lectura_Descripcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lectura_Descripcion2ActionPerformed

    private void Lectura_Precio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lectura_Precio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lectura_Precio2ActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        Frescos carga= new Frescos();
       
        int paso;
        double paso1;
        SimpleDateFormat sdf = new SimpleDateFormat ("dd-mm-yyyy");
        carga.setCodigo(Integer.parseInt(jtfCodigo.getText()));
        carga.setNombre(Lectura_Nombre.getText());
        carga.setDescripcion(Lectura_Descripcion.getText());
        carga.setFechaEnvasado((Lectura_Fecha.getDate()));
        carga.setFechaCaducidad(Lectura_Fecha1.getDate());
       paso= Integer.parseInt(Lectura_Lote.getText());
        carga.setNumeroDeLote(paso);
        carga.setPaisOrigen(Lectura_Pais.getText());
        paso1= Double.parseDouble(Lectura_Precio.getText());
        carga.setPrecio(paso1);
        registros.put(Integer.parseInt(jtfCodigo.getText()), carga);
        limpiarCampo();
    }//GEN-LAST:event_GuardarActionPerformed
    private void limpiarCampo(){
        jtfCodigo.setText("");
        Lectura_Nombre.setText("");
        Lectura_Descripcion.setText("");
        Lectura_Lote.setText("");
        Lectura_Pais.setText("");
        Lectura_Precio.setText(""); 
    }
    
    private void limpiarCampoRefrigerados(){
        jtfCodigoRefrigerados.setText("");
        Lectura_Nombre1.setText("");
        Lectura_Descripcion1.setText("");
        Lectura_Lote1.setText("");
        jtfCodigoDeOrganismo.setText("");
        Lectura_Precio1.setText(""); 
    }
    
    private void limpiarCampoCongelados(){
        jtfCodigoCongelados.setText("");
        Lectura_Nombre2.setText("");
        Lectura_Descripcion2.setText("");
        Lectura_Lote2.setText("");
        Lectura_Temperatura.setText("");
        Lectura_Precio2.setText(""); 
    }
    
    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
     // escribir_cargados(registros);
        escribir_cargados();
        new Principal().setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        int codigof= Integer.parseInt(jtfCodigo.getText());
        Frescos fm= (Frescos)registros.get(codigof);
        if(fm!=null){
             Lectura_Nombre.setText(fm.getNombre());
             Lectura_Descripcion.setText(fm.getDescripcion());
             Lectura_Fecha.setDate(fm.getFechaEnvasado());
             Lectura_Fecha1.setDate(fm.getFechaCaducidad());
             Lectura_Lote.setText(fm.getNumeroDeLote() +"");
             Lectura_Pais.setText(fm.getPaisOrigen());
             Lectura_Precio.setText(fm.getPrecio() +"");
        }
        else{
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
        }
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jtfCodigoRefrigeradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoRefrigeradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoRefrigeradosActionPerformed

    private void buscarRefrigeradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarRefrigeradosActionPerformed
        // TODO add your handling code here:
        int codigof= Integer.parseInt(jtfCodigoRefrigerados.getText());
        Refrigerados rm= (Refrigerados)registros.get(codigof);
        if(rm!=null){
              Lectura_Nombre1.setText(rm.getNombre());
              Lectura_Descripcion1.setText(rm.getDescripcion());
              Lectura_Fecha3.setDate(rm.getFechaCaducidad());
              Lectura_Lote1.setText(rm.getNumeroDeLote() +"");
              jtfCodigoDeOrganismo.setText(rm.getCodOrganismo());
              Lectura_Precio1.setText(rm.getPrecio() +"");
        
        }
        else{
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
        }
    }//GEN-LAST:event_buscarRefrigeradosActionPerformed

    private void EliminarRefrigeradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarRefrigeradoActionPerformed
        // TODO add your handling code here:
        registros.remove(Integer.parseInt(jtfCodigoRefrigerados.getText()));
    }//GEN-LAST:event_EliminarRefrigeradoActionPerformed

    private void jtfCodigoCongeladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoCongeladosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoCongeladosActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        Frescos f= (Frescos)registros.get(Integer.parseInt(jtfCodigo.getText()));
        f.setNombre(Lectura_Nombre.getText());
        f.setDescripcion(Lectura_Descripcion.getText());
        f.setFechaEnvasado((Lectura_Fecha.getDate()));
        f.setFechaCaducidad(Lectura_Fecha1.getDate());
         int paso= Integer.parseInt(Lectura_Lote.getText());
        f.setNumeroDeLote(paso);
        f.setPaisOrigen(Lectura_Pais.getText());
        double paso1= Double.parseDouble(Lectura_Precio.getText());
        f.setPrecio(paso1);
        limpiarCampo();
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        registros.remove(Integer.parseInt(jtfCodigo.getText()));
    }//GEN-LAST:event_EliminarActionPerformed

    private void jtfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusLost
        // TODO add your handling code here:
       try{ 
       Integer.parseInt(jtfCodigo.getText());
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Usted debe ingresar un nro.");
           jtfCodigo.requestFocus();
       }
      
        
    }//GEN-LAST:event_jtfCodigoFocusLost

    private void Lectura_NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_NombreFocusLost
        // TODO add your handling code here:
        if(Lectura_Nombre.getText().length()==0){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar un Nombre");
           Lectura_Nombre.requestFocus();
        }
        
    }//GEN-LAST:event_Lectura_NombreFocusLost

    private void Lectura_FechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_FechaFocusLost
        // TODO add your handling code here:
        
        if(Lectura_Fecha.getDate()==null){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar una Fecha");
           Lectura_Fecha.requestFocus();
            
        }
    }//GEN-LAST:event_Lectura_FechaFocusLost

    private void modificarRefrigeradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarRefrigeradosActionPerformed
        // TODO add your handling code here:
        Refrigerados r= (Refrigerados)registros.get(Integer.parseInt(jtfCodigoRefrigerados.getText()));
        r.setNombre(Lectura_Nombre1.getText());
        r.setDescripcion(Lectura_Descripcion1.getText());
        r.setFechaCaducidad(Lectura_Fecha3.getDate());
         int paso= Integer.parseInt(Lectura_Lote1.getText());
        r.setNumeroDeLote(paso);
        r.setCodOrganismo(jtfCodigoDeOrganismo.getText());
        double paso1= Double.parseDouble(Lectura_Precio1.getText());
        r.setPrecio(paso1);
        limpiarCampoRefrigerados();
    }//GEN-LAST:event_modificarRefrigeradosActionPerformed

    private void Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar1ActionPerformed
        // TODO add your handling code here:
     Refrigerados carga= new Refrigerados();
       
        int paso;
        double paso1;
        SimpleDateFormat sdf = new SimpleDateFormat ("dd-mm-yyyy");
        carga.setCodigo(Integer.parseInt(jtfCodigoRefrigerados.getText()));
        carga.setNombre(Lectura_Nombre1.getText());
        carga.setDescripcion(Lectura_Descripcion1.getText());
        carga.setFechaCaducidad(Lectura_Fecha3.getDate());
        paso= Integer.parseInt(Lectura_Lote1.getText());
        carga.setNumeroDeLote(paso);
        carga.setCodOrganismo(jtfCodigoDeOrganismo.getText());
        paso1= Double.parseDouble(Lectura_Precio1.getText());
        carga.setPrecio(paso1);
        registros.put(Integer.parseInt(jtfCodigoRefrigerados.getText()), carga);
        limpiarCampoRefrigerados();   
    }//GEN-LAST:event_Guardar1ActionPerformed

    private void BuscarCongeladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCongeladosActionPerformed
        // TODO add your handling code here:
      int codigof= Integer.parseInt(jtfCodigoCongelados.getText());
        Congelados cm= (Congelados)registros.get(codigof);
        if(cm!=null){
              Lectura_Nombre2.setText(cm.getNombre());
              Lectura_Descripcion2.setText(cm.getDescripcion());
              Lectura_Fecha4.setDate(cm.getFechaCaducidad());
              Lectura_Lote2.setText(cm.getNumeroDeLote() +"");
              Lectura_Temperatura.setText(cm.getTempRecomendada() +"");
              Lectura_Precio2.setText(cm.getPrecio() +"");
        
        }
        else{
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
        }  
    }//GEN-LAST:event_BuscarCongeladosActionPerformed

    private void EliminarCongeladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCongeladosActionPerformed
        // TODO add your handling code here:
         registros.remove(Integer.parseInt(jtfCodigoCongelados.getText()));
    }//GEN-LAST:event_EliminarCongeladosActionPerformed

    private void ModificarCongeladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarCongeladosActionPerformed
        // TODO add your handling code here:
      Congelados c= (Congelados)registros.get(Integer.parseInt(jtfCodigoCongelados.getText()));
        c.setNombre(Lectura_Nombre1.getText());
        c.setDescripcion(Lectura_Descripcion1.getText());
        c.setFechaCaducidad(Lectura_Fecha3.getDate());
         int paso= Integer.parseInt(Lectura_Lote1.getText());
        c.setNumeroDeLote(paso);
        c.setTempRecomendada(Double.parseDouble(Lectura_Temperatura.getText()));
        double paso1= Double.parseDouble(Lectura_Precio2.getText());
        c.setPrecio(paso1);
        limpiarCampoCongelados();  
    }//GEN-LAST:event_ModificarCongeladosActionPerformed

    private void Guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar2ActionPerformed
        // TODO add your handling code here:
         Congelados carga= new Congelados();
       
        int paso;
        double paso1;
        SimpleDateFormat sdf = new SimpleDateFormat ("dd-mm-yyyy");
        carga.setCodigo(Integer.parseInt(jtfCodigoCongelados.getText()));
        carga.setNombre(Lectura_Nombre2.getText());
        carga.setDescripcion(Lectura_Descripcion2.getText());
        carga.setFechaCaducidad(Lectura_Fecha4.getDate());
        paso= Integer.parseInt(Lectura_Lote2.getText());
        carga.setNumeroDeLote(paso);
        paso1= Double.parseDouble(Lectura_Precio2.getText());
        carga.setPrecio(paso1);
        registros.put(Integer.parseInt(jtfCodigo.getText()), carga);
        limpiarCampoCongelados();
    }//GEN-LAST:event_Guardar2ActionPerformed

    private void Lectura_DescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_DescripcionFocusLost
        // TODO add your handling code here:
        if(Lectura_Descripcion.getText().length()==0){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar un Nombre");
           Lectura_Descripcion.requestFocus();
        }
    }//GEN-LAST:event_Lectura_DescripcionFocusLost

    private void Lectura_Fecha1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Fecha1FocusLost
        // TODO add your handling code here:
        if(Lectura_Fecha1.getDate()==null){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar una Fecha");
           Lectura_Fecha1.requestFocus();
            
        }
    }//GEN-LAST:event_Lectura_Fecha1FocusLost

    private void Lectura_LoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_LoteFocusLost
        // TODO add your handling code here:
        try{ 
       Integer.parseInt(Lectura_Lote.getText());
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Usted debe ingresar un nro.");
           Lectura_Lote.requestFocus();
       }  
    }//GEN-LAST:event_Lectura_LoteFocusLost

    private void Lectura_PaisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_PaisFocusLost
        // TODO add your handling code here:
        if(Lectura_Pais.getText().length()==0){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar un Nombre");
           Lectura_Pais.requestFocus();
        }
    }//GEN-LAST:event_Lectura_PaisFocusLost

    private void Lectura_PrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_PrecioFocusLost
        // TODO add your handling code here:
          try{ 
       Double.parseDouble(Lectura_Precio.getText());
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Usted debe ingresar un nro.");
           Lectura_Precio.requestFocus();
       }  
    }//GEN-LAST:event_Lectura_PrecioFocusLost

    private void jtfCodigoRefrigeradosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoRefrigeradosFocusLost
        // TODO add your handling code here:
         try{ 
       Integer.parseInt(jtfCodigoRefrigerados.getText());
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Usted debe ingresar un nro.");
           jtfCodigoRefrigerados.requestFocus();
       }
    }//GEN-LAST:event_jtfCodigoRefrigeradosFocusLost

    private void Lectura_Nombre1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Nombre1FocusLost
        // TODO add your handling code here:
         if(Lectura_Nombre1.getText().length()==0){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar un Nombre");
           Lectura_Nombre1.requestFocus();
        }
    }//GEN-LAST:event_Lectura_Nombre1FocusLost

    private void Lectura_Descripcion1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Descripcion1FocusLost
        // TODO add your handling code here:
         if(Lectura_Descripcion1.getText().length()==0){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar un Nombre");
           Lectura_Descripcion1.requestFocus();
        }
    }//GEN-LAST:event_Lectura_Descripcion1FocusLost

    private void Lectura_Fecha3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Fecha3FocusLost
        // TODO add your handling code here:
        if(Lectura_Fecha3.getDate()==null){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar una Fecha");
           Lectura_Fecha3.requestFocus();
            
        }
    }//GEN-LAST:event_Lectura_Fecha3FocusLost

    private void Lectura_Lote1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Lote1FocusLost
        // TODO add your handling code here:
         try{ 
       Integer.parseInt(Lectura_Lote1.getText());
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Usted debe ingresar un nro.");
           Lectura_Lote1.requestFocus();
       }
    }//GEN-LAST:event_Lectura_Lote1FocusLost

    private void jtfCodigoDeOrganismoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoDeOrganismoFocusLost
        // TODO add your handling code here:
        if(jtfCodigoDeOrganismo.getText().length()==0){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar un Nombre");
           jtfCodigoDeOrganismo.requestFocus();
        }
    }//GEN-LAST:event_jtfCodigoDeOrganismoFocusLost

    private void Lectura_Precio1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Precio1FocusLost
        // TODO add your handling code here:
         try{ 
       Double.parseDouble(Lectura_Precio1.getText());
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Usted debe ingresar un nro.");
           Lectura_Precio1.requestFocus();
       }  
    }//GEN-LAST:event_Lectura_Precio1FocusLost

    private void jtfCodigoCongeladosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoCongeladosFocusLost
        // TODO add your handling code here:
       try{ 
       Integer.parseInt(jtfCodigoCongelados.getText());
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Usted debe ingresar un nro.");
           jtfCodigoCongelados.requestFocus();
       }  
    }//GEN-LAST:event_jtfCodigoCongeladosFocusLost

    private void Lectura_Nombre2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Nombre2FocusLost
        // TODO add your handling code here:
        if(Lectura_Nombre2.getText().length()==0){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar un Nombre");
           Lectura_Nombre2.requestFocus();
        }
    }//GEN-LAST:event_Lectura_Nombre2FocusLost

    private void Lectura_Descripcion2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Descripcion2FocusLost
        // TODO add your handling code here:
        if(Lectura_Descripcion2.getText().length()==0){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar un Nombre");
           Lectura_Descripcion2.requestFocus();
        }
    }//GEN-LAST:event_Lectura_Descripcion2FocusLost

    private void Lectura_Fecha4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Fecha4FocusLost
        // TODO add your handling code here:
       if(Lectura_Fecha4.getDate()==null){
        
            JOptionPane.showMessageDialog(this, "Usted debe ingresar una Fecha");
           Lectura_Fecha4.requestFocus();
            
        } 
    }//GEN-LAST:event_Lectura_Fecha4FocusLost

    private void Lectura_Lote2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Lote2FocusLost
        // TODO add your handling code here:
         try{ 
       Integer.parseInt(Lectura_Lote2.getText());
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Usted debe ingresar un nro.");
           Lectura_Lote2.requestFocus();
       }
    }//GEN-LAST:event_Lectura_Lote2FocusLost

    private void Lectura_TemperaturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_TemperaturaFocusLost
        // TODO add your handling code here:
       try{ 
       Double.parseDouble(Lectura_Temperatura.getText());
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Usted debe ingresar un nro.");
           Lectura_Temperatura.requestFocus();
       }    
    }//GEN-LAST:event_Lectura_TemperaturaFocusLost

    private void Lectura_Precio2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lectura_Precio2FocusLost
        // TODO add your handling code here:
         try{ 
       Double.parseDouble(Lectura_Precio2.getText());
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Usted debe ingresar un nro.");
           Lectura_Precio2.requestFocus();
       }  
    }//GEN-LAST:event_Lectura_Precio2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargaDeProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton BuscarCongelados;
    private javax.swing.JLabel Cabecera;
    private javax.swing.JLabel Codigo_Organismo;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Descripcion1;
    private javax.swing.JLabel Descripcion2;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton EliminarCongelados;
    private javax.swing.JButton EliminarRefrigerado;
    private javax.swing.JLabel Fecha_Caducidad;
    private javax.swing.JLabel Fecha_Caducidad1;
    private javax.swing.JLabel Fecha_Caducidad2;
    private javax.swing.JLabel Fecha_Envasado;
    private javax.swing.JTabbedPane Frescos;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar1;
    private javax.swing.JButton Guardar2;
    private javax.swing.JTextField Lectura_Descripcion;
    private javax.swing.JTextField Lectura_Descripcion1;
    private javax.swing.JTextField Lectura_Descripcion2;
    private com.toedter.calendar.JDateChooser Lectura_Fecha;
    private com.toedter.calendar.JDateChooser Lectura_Fecha1;
    private com.toedter.calendar.JDateChooser Lectura_Fecha3;
    private com.toedter.calendar.JDateChooser Lectura_Fecha4;
    private javax.swing.JTextField Lectura_Lote;
    private javax.swing.JTextField Lectura_Lote1;
    private javax.swing.JTextField Lectura_Lote2;
    private javax.swing.JTextField Lectura_Nombre;
    private javax.swing.JTextField Lectura_Nombre1;
    private javax.swing.JTextField Lectura_Nombre2;
    private javax.swing.JTextField Lectura_Pais;
    private javax.swing.JTextField Lectura_Precio;
    private javax.swing.JTextField Lectura_Precio1;
    private javax.swing.JTextField Lectura_Precio2;
    private javax.swing.JTextField Lectura_Temperatura;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton ModificarCongelados;
    private javax.swing.JLabel Nombre_Producto;
    private javax.swing.JLabel Nombre_Producto1;
    private javax.swing.JLabel Nombre_Producto2;
    private javax.swing.JLabel Numero_Lote;
    private javax.swing.JLabel Numero_Lote1;
    private javax.swing.JLabel Numero_Lote2;
    private javax.swing.JLabel Pais_Origen;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Precio1;
    private javax.swing.JLabel Precio2;
    private javax.swing.JPanel Productos_Congelados;
    private javax.swing.JPanel Productos_Frescos;
    private javax.swing.JPanel Productos_Refrigerados;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel Temperatura_Recomendada;
    private javax.swing.JButton buscarRefrigerados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfCodigoCongelados;
    private javax.swing.JTextField jtfCodigoDeOrganismo;
    private javax.swing.JTextField jtfCodigoRefrigerados;
    private javax.swing.JButton modificarRefrigerados;
    // End of variables declaration//GEN-END:variables
}
